site_name: Janet Mutua
# site_url: https://mydomain.org/mysite
theme:
  name: material
  language: en

  font:
    text: Roboto
    code: Roboto Mono

  features: 
    # Header
    - header.autohide
    - announce.dismiss

    # Navigation
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - navigation.footer

    # Search
    - search.suggest
    - search.share
    - search.highlight

    # Content and Code
    - content.code.copy
    - content.tabs.link
    # - content.code.annotate
    # - content.code.hint

  nav:
    - Home: index.md
    - About: about.md
    - Blog: blog.md
    - Knowledge Base:
      - Start here: knowledge_base/overview.md
      - AI Agents:
          - Overview: overview.md
          - RAG: AI_agents/RAG.md
          - Agentic AI: AI_agents/agentic_ai.md
          - Agent Frameworks: AI_agents/agent_frameworks.md
      - CI/CD:
          - Overview: AI%20Engineering/overview.md
          - Data Engineering: AI%20Engineering/data_engineering.md
          - Model Engineering: AI%20Engineering/model_engineering.md
          - Deployment: AI%20Engineering/deployment.md



  plugins:
    - search
    - typeset


  markdown_extensions:
    # - codehilite
    # - footnotes
    # - md_in_html
    - toc:
        permalink: true

  copyright: Copyright &copy; 2025 Janet Mutua
    # icon: material/copyright
    # name: Janet Mutua
    # year: 2023
    # link: https://janetmutua.com

  extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/JanetMutua
        name: GitHub
      - icon: fontawesome/brands/twitter
        link: https://x.com/mu_mbua_
        name: Twitter
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/janetmutua/
        name: LinkedIn
      - icon: fontawesome/brands/DEV 
        link: https://dev.to/janetmutua
        name: DEV.to
      - icon: fontawesome/brands/medium
        link: https://medium.com/@janetmutua
        name: Medium        


  palette:

    # Dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode


    # Light mode
    - scheme: default
      primary: deep purple
      accent: deep orange
      toggle: 
        icon: material/weather-sunny
        name: Switch to dark mode
